---
- name: Create jenkins container
  docker_container:
    name: jenkins
    image: jenkins/jenkins:alpine
    state: started
    restart_policy: unless-stopped
    ports:
      - "80:8080"
      - "5000:5000"