---
- name: install docker
  yum:
    name='docker'
    state=latest
  become: yes

- name: Ensure group docker exists
  group:
    name: docker
    state: present
  become: yes

- name: Get current user
  become: no
  shell: whoami
  register: current_non_root_user

- name: Add the current user to the docker group
  user:
    name: "{{ current_non_root_user.stdout }}"
    shell: /bin/bash
    groups: docker
    append: yes
  become: yes

- name: start docker service
  service:
    name=docker
    state=started
    enabled=yes
  become: yes

- name: Install docker-compose
  pip:
    name: docker-compose
    state: latest
  become: yes